---

version: 1
disable_existing_loggers: true

formatters:
  console_format:
    format: "%(asctime)s :: %(levelname)s :: %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
  file_format:
    format: "%(asctime)s :: %(name)s :: %(levelname)s :: %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: console_format
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: file_format
    filename: info.log
    when: midnight
    backupCount: 20
    encoding: utf8

root:
  level: DEBUG
  handlers: [console_handler, file_handler]
  propagate: no

